# Generated by Django 5.2.8 on 2025-12-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Укажите вашу страну",
                max_length=35,
                null=True,
                verbose_name="Страна",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите ваше фото",
                null=True,
                upload_to="users/avatars/",
                verbose_name="Аватар",
            ),
        ),
    ]
