# Generated by Django 5.2.8 on 2025-11-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blog/blog_previews",
                verbose_name="Превью изображения",
            ),
        ),
    ]
